### ISSUE TITLE
forceStopTask() not work

### ISSUE THREAD

**Issue by DimaDDM** [bertrandmartel/speed-test-lib#37]
Hello again!
When i'm using forceStopTask for stop all task ... task keeps executing.
This bug work in methods
```
startUploadRepeat
startDownloadRepeat
```
Reports stopping but percent progress keep increment in` IRepeatListener (onReport)`!

**Comment by bertrandmartel** [comment]
Thank you for reporting this bug, this has been fixed in 1.30. Note that there is a callback naming change in 1.30 for repeat listener : 

* `onFinished` become `onCompletion`

For the speed test listener, there is only one callback for progress (`onProgress`), one for error (`onError`) and one for completion (`onCompletion`)

Check the [release note](https://github.com/bertrandmartel/speed-test-lib/releases/tag/1.30)

**Comment by DimaDDM** [comment]
So many fixes! Looks like best day of my life :) Thanks!
