### ISSUE TITLE
onCompletion not called

### ISSUE THREAD

**Issue by DimaDDM** [bertrandmartel/speed-test-lib#38]
Hello. After call `forceStopTask()` onCompletion not called. I think it's bug.
P.S.
This for
`startDownloadRepeat` or `startUploadRepeat`

**Comment by bertrandmartel** [comment]
This is not a bug for the speed test listener `ISpeedTestListener`, the right behavior is that `onCompletion` is called when the download/upload is complete. If `forceStopTask()` is called unexpectedly it triggers `onInterruption` callback. `onInterruption` exactly means that the task was interrupted because of `forceStopTask()` .

```
@Override
public void onInterruption() {
    //triggered when forceStopTask is called
}
```

This helps to distinguish the `onError` which occurs when something unexpected happened from the `onInterruption` when you expect the speed test to stop.

**Comment by DimaDDM** [comment]
Okay. Can you add in `ISpeedTestListener` finish callback? Thanks.

**Comment by bertrandmartel** [comment]
`onCompletion` indicates that download/upload is complete
`onInterruption` indicates that the download/upload has been stopped

**Comment by bertrandmartel** [comment]
`onInterruption` will be removed in next release. `onCompletion` will be called instead
